### ISSUE TITLE
Server-sent events

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#17] opened 2016-11-29 13:32 UTC
One of the references in the OIPF Web Standards TV Profile (http://www.oipf.tv/docs/OIPF-T1-R2-Specification-Volume5a-Web-Standards-TV-Profile-v2_3-2014-01-24.pdf ) (with HbbTV updates) that isn't in the November 28th 2016 version of the Web Media API (https://w3c.github.io/webmediaapi/#normative-references ) is the following;

[SSE-20121211]
Ian Hickson. Server-Sent Events. 11 December 2012. W3C Candidate Recommendation. URL: http://www.w3.org/TR/2012/CR-eventsource-20121211/

**Comment by davemevans** [comment] 2016-11-29 13:39
Duplicate of #6?

**Comment by jpiesing** [comment] 2016-11-29 14:18
This was published as a W3C Recommendation in 2015 there is a note that " No one in the Web Platform Working Group is actively working on this specification. For the latest version of Server-sent Events use the WHATWG's Living Standard. "

**Comment by mavgit** [comment] 2016-12-14 09:28
We should close this as duplicate of #6

**Comment by davemevans** [comment] 2017-02-06 08:20
@jpiesing Please can you close this if you are happy it is a duplicate of #6?

**Closed as completed** 2017-02-06 11:12 UTC
Labels: duplicate
